### ISSUE TITLE
Fatal error while accessing /report/eventlist/index.php

### ISSUE THREAD

**Issue by gabrielrosset** [jfruitet/moodle_referentiel_m27#1]
Hello,
I've got this error directly when I click : "reports>event list" from admin menu : 
"
Fatal error: Class 'core\event\import_intance' not found in ~\mod\referentiel\classes\event\import_instance.php on line 37
"
Error displayed into Moodle 2.9.4 with those plugins versions : 
block_referentiel : version 2014110300
mod_referentiel : version 2015070602
report_referentiel : version 2013061401
Kind regards.

**Comment by jfruitet** [comment]
Thanx for this info.
_I have made the bug correction in source.
You can also write down the bug correction yourself.
Replace the line 37 of ./mod/referentiel/classes/event/import_instance.php
by :_
class import_intance extends \core\event\base {

Jean.

**Comment by gabrielrosset** [comment]
I've tried this but if I remember well this cause another fatal error too

**Comment by jfruitet** [comment]
Hi,
I have tested the correction in
"Site Administration / Report / Events list" 
with "Skills repository component" filter, 
but I can't get any more error on my server (except few message strings that I have since added).
Can you send me a screen copy of the error directly to jean.fruitet@free.fr ?

Regards.
Jean.

**Comment by gabrielrosset** [comment]
You're right Jean the bug is fixed, thank you for that.
